version: '3.7'

services:
  auth:
    image: ${IMAGE_URL}
    build:
      context: .
      args:
        - TARGET_ALIAS
        - TARGET_IMAGE_TAG
        - SERVICE
        - TARGET_PROJECT_ID
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file:
      - ".env.local.yml"
    ports:
      - ${TARGET_LOCAL_PORT}:${TARGET_REMOTE_PORT}
